name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: prod
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Delete Old Container
        run: docker rm -f chainlinkContainerServer || true

      - name: Run docker container
        env:
          DB_TYPE: ${{ secrets.DB_TYPE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          APP_PORT: ${{ secrets.APP_PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
          EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
        run: |
          docker run --name chainlinkContainerServer -p $APP_PORT:80 \
            -e DB_TYPE=$DB_TYPE \
            -e DB_HOST=$DB_HOST \
            -e DB_NAME=$DB_NAME \
            -e DB_PORT=$DB_PORT \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION=$AWS_REGION \
            -e AWS_BUCKET_NAME=$AWS_BUCKET_NAME \
            -e APP_PORT=$APP_PORT \
            -e SECRET_KEY=$SECRET_KEY \
            -e EMAIL_HOST=$EMAIL_HOST \
            -e EMAIL_PORT=$EMAIL_PORT \
            -e EMAIL_USER=$EMAIL_USER \
            -e EMAIL_PASSWORD=$EMAIL_PASSWORD \
            -e AWS_S3_REGION=$AWS_S3_REGION \
            -d ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
